name: Ktlint

on:
  push:
    branches: [master] # Just in case master was not up to date while merging PR
  pull_request:
    types: [opened, synchronize]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create APIKEY.PROPERTIES File
        env:
          API_KEY: ${{ secrets.APIKEY }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIAAPIKEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIAAPPID }}
        run: |
          touch apikey.properties
          echo "API_KEY=$API_KEY" >> apikey.properties
          echo "ALGOLIA_API_KEY=$ALGOLIA_API_KEY" >> apikey.properties
          echo "ALGOLIA_APP_ID=$ALGOLIA_APP_ID" >> apikey.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: ktlint
        run: ./gradlew ktlintCheck

      - uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: ./**/build/reports/ktlint/